### ISSUE TITLE
accessibility-fixer-upper

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/accessibility-fixer-upper#1]
Having trouble with the visual difference of screenshot @320px
@mackenzierose

**Comment by MacKenzieRose** [comment]
I looked through your code, and the Markbot screenshots; I'm confident that this is an old screenshot issue, and not that you haven't understood the content.

@muxlowc Can you take a look, and if you agree, enter this grade manually?

Cheers!
MacKenzie

**Comment by muxlowc** [comment]
@VanshitaGandhi looks good to me, ill give you the grade manually - thanks Mackenzie!

**Comment by VanshitaGandhi** [comment]
Thank you! @muxlowc @MacKenzieRose
